
import re
from typing import Tuple

# Simple term lists for prefilter
SENSITIVE_TERMS = [
    r"\bnude\b", r"\bnudity\b", r"\bnsfw\b", r"\bexplicit\b",
    r"\bviolence\b", r"\bgore\b", r"\brape\b", r"\bterror\b",
    r"\bsteal(?:ing)?\b", r"\bdrugs?\b", r"\bweapon\b", r"\bmurder\b",
    r"\bkill(?:ing|ed)?\b", r"\bhomicide\b", r"\bmanslaughter\b",
    r"\bassault\b", r"\bbattery\b", r"\bdomestic abuse\b",
    r"\babuse\b", r"\btorture\b", r"\bmutilat(?:e|ion|ed)\b",
    r"\bbehead(?:ing|ed)?\b", r"\bdecapitat(?:e|ion|ed)\b",
    r"\bdismember(?:ment|ed|ing)?\b", r"\bstab(?:bing|bed)?\b",
    r"\bshoot(?:ing|er|s)?\b", r"\bgun\b", r"\bfirearm(?:s)?\b",
    r"\bpistol\b", r"\brifle\b", r"\bshotgun\b", r"\bsniper\b",
    r"\bmachine ?gun\b", r"\bsubmachine\b", r"\bgrenade\b",
    r"\bexplosive\b", r"\bexplosion\b", r"\bbomb\b", r"\bbomb(?:ing|er)?\b",
    r"\bmolotov\b", r"\barson\b", r"\bfirebomb\b", r"\bbullet(?:s)?\b",
    r"\bammo\b", r"\bammunition\b", r"\btaser\b", r"\bstun gun\b",
    r"\bknife\b", r"\bdagger\b", r"\bmachete\b", r"\baxe\b",
    r"\bhatchet\b", r"\bspear\b", r"\bbow\b", r"\barrow\b",
    r"\bcrossbow\b", r"\bbrass knuckles\b", r"\bknuckleduster\b",
    r"\bchainsaw\b", r"\bclub\b", r"\bbaton\b",
    r"\bpoison\b", r"\btoxic\b", r"\bvenom\b", r"\bcyanide\b",
    r"\bricin\b", r"\bnerve gas\b", r"\bchemical weapon(?:s)?\b",
    r"\bbiological weapon(?:s)?\b", r"\bnuclear\b", r"\bnuke\b",
    r"\bradiation\b", r"\bfal(?:l|l)out\b", r"\bdirty bomb\b",
    r"\bgenocide\b", r"\bethnic cleansing\b", r"\bmassacre\b",
    r"\bexecution\b", r"\blynch(?:ing|ed)?\b", r"\bstrangulat(?:e|ion|ed)\b",
    r"\bsuffocat(?:e|ion|ed)\b", r"\bchoke(?:d|hold|ing)?\b",
    r"\bterroris(?:m|t|ts)\b", r"\bextremis(?:m|t|ts)\b",
    r"\bjihad\b", r"\binsurgency\b", r"\bmilitant(?:s)?\b",
    r"\bkidnap(?:ping|ped|per|pers)?\b", r"\babduct(?:ion|ed|or|ors)?\b",
    r"\bhuman traffick(?:ing|er|ers)?\b", r"\bslavery\b",
    r"\benslave(?:d|ment)?\b", r"\bhostage\b",
    r"\bblackmail\b", r"\bextort(?:ion|ed|ing)?\b",
    r"\bbribe(?:ry|d|s)?\b", r"\bcorruption\b",
    r"\bmoney laundering\b", r"\bembezzl(?:e|ement|ed)\b",
    r"\bfraud\b", r"\bscam(?:s|mer|ming)?\b",
    r"\bforg(?:e|ery|ed)\b", r"\bcounterfeit(?:ing|ed)?\b",
    r"\bpiracy\b", r"\bbootleg(?:ging|ged)?\b",
    r"\brob(?:bery|bed|bing)\b", r"\bmug(?:ging|ged)?\b",
    r"\btheft\b", r"\bthief\b", r"\bburglar(?:y|ize|ized)?\b",
    r"\bshoplift(?:ing|er|ed)?\b", r"\bvandal(?:ism|ize|ized)\b",
    r"\btrespass(?:ing|er|ed)?\b", r"\barson\b",
    r"\bdrug(?:s)?\b", r"\bnarcotic(?:s)?\b",
    r"\bcocaine\b", r"\bcrack\b", r"\bheroin\b",
    r"\bmeth(?:amphetamine)?\b", r"\bice\b", r"\bcrystal meth\b",
    r"\bfentanyl\b", r"\bopioid(?:s)?\b", r"\boxycodone\b",
    r"\bhydrocodone\b", r"\bmorphine\b", r"\bcodeine\b",
    r"\boxycontin\b", r"\bbenzo(?:diazepines?)?\b", r"\bxanax\b",
    r"\bvalium\b", r"\bativan\b", r"\bklonopin\b",
    r"\bsteroid(?:s)?\b", r"\bdoping\b", r"\bghb\b", r"\brohypnol\b",
    r"\bketamine\b", r"\blsd\b", r"\bacid\b", r"\becstasy\b",
    r"\bmdma\b", r"\bshrooms\b", r"\bpsilocybin\b",
    r"\bmarijuana\b", r"\bweed\b", r"\bcannabis\b", r"\bhash\b",
    r"\bopium\b", r"\bpoppy\b", r"\bvape\b", r"\bvaping\b",
    r"\binhalant(?:s)?\b", r"\bglue sniff(?:ing)?\b",
    r"\bdrug deal(?:ing|er|ers)?\b", r"\bdistribution\b",
    r"\bsmuggl(?:e|ing|er|ers)\b", r"\bcontraband\b", r"\bcartel\b",
    r"\bbrothel\b", r"\bprostitut(?:e|ion|ed)\b", r"\bescort(?:s)?\b",
    r"\bporn\b", r"\bpornograph(?:y|ic)\b", r"\berotica\b",
    r"\b18\+?\b", r"\badult content\b", r"\bsex\b", r"\bsexual\b",
    r"\bintercourse\b", r"\borgasm\b", r"\bclimax\b",
    r"\bbreast(?:s)?\b", r"\bnipple(?:s)?\b", r"\bareola(?:e|s)?\b",
    r"\bbutt(?:s|ocks)?\b", r"\banal\b", r"\boral sex\b",
    r"\bblowjob\b", r"\bhandjob\b", r"\bthreesome\b", r"\bfoursome\b",
    r"\bgangbang\b", r"\bcuckold\b", r"\bswinger(?:s)?\b",
    r"\bstrip(?:per|tease|ping)?\b", r"\blap dance\b",
    r"\bdominatrix\b", r"\bsubmissive\b", r"\bdominance\b",
    r"\bbdsm\b", r"\bbondage\b", r"\bfetish\b", r"\bkink(?:y)?\b",
    r"\bdildo(?:s)?\b", r"\bvibrator(?:s)?\b", r"\blingerie\b",
    r"\bcondom(?:s)?\b", r"\bpregnan(?:t|cy)\b", r"\bimpregnat(?:e|ed)\b",
    r"\binsest\b", r"\bmolest(?:ation|ed|er|ers)?\b",
    r"\bsexual assault\b", r"\bvoyeur(?:ism|istic)?\b",
    r"\bexhibition(?:ism|ist)\b", r"\bcam ?girl\b", r"\bcam ?boy\b",
    r"\bonlyfans\b", r"\bsugar daddy\b", r"\bsugar baby\b",
    r"\bescort service\b", r"\bcall girl\b", r"\bcourtesan\b",
    r"\bnecrophilia\b", r"\bbestiality\b", r"\bzoophilia\b",
    r"\bpublic indecenc(?:y|e)\b", r"\bobscen(?:e|ity)\b",
    r"\bindecent\b", r"\blewd\b",
    r"\bself-?harm\b", r"\bsuicid(?:e|al)\b", r"\bkill myself\b",
    r"\bkill yourself\b", r"\bself mutilation\b", r"\bcut(?:ting)?\b",
    r"\bslit(?:ting)? wrists\b", r"\bhanging\b", r"\boverdose\b",
    r"\bpoison myself\b", r"\bjump off\b", r"\bnoose\b",
    r"\bcyberbully(?:ing)?\b", r"\bharass(?:ment|ed|ing)\b",
    r"\bhate speech\b", r"\bthreat(?:en|s|ening)\b",
    r"\bdoxx(?:ing|ed)?\b", r"\bswat(?:ting|ted)?\b",
    r"\bhack(?:ing|er|ers)?\b", r"\bmalware\b", r"\bvirus\b",
    r"\bransomware\b", r"\bspyware\b", r"\bkeylogger\b",
    r"\bphish(?:ing|ed)?\b", r"\bidentity theft\b",
    r"\bforbidden\b", r"\billegal\b", r"\bcontrary to law\b",
    r"\bunlawful\b", r"\bcriminal\b", r"\bcrime\b",
    r"\bcopyright infringe(?:ment|)\b", r"\bplagiar(?:ism|ize|ized)\b",
    r"\bdeepfake\b", r"\bimpersonat(?:e|ion)\b",
    r"\bexploit(?:ation|ative)?\b", r"\bchild exploitation\b",
    r"\bcsam\b", r"\bminor sexual(?:ization|ised|ized)\b",
    r"\bhuman sacrifice\b", r"\bcannibal(?:ism|istic)?\b",
    r"\bgorefest\b", r"\bsplatter\b", r"\bbloodbath\b",
    r"\bbloody\b", r"\bbloodlust\b", r"\bskull crush\b",
    r"\bflay(?:ing|ed)?\b", r"\bimpale(?:ment|d|s)?\b",
    r"\bgarrote\b", r"\bwaterboard(?:ing|ed)?\b",
    r"\belectrocute(?:d|ion)?\b", r"\bmaim(?:ed|ing)?\b",
    r"\bslaughter\b", r"\bbutcher(?:ing|ed)?\b",
    r"\bstone(?:d|ing)\b", r"\bcrucifix(?:ion|)\b",
    r"\bdRAWN and quartered\b", r"\bquarter(?:ing|ed)\b",
    r"\bterror cell\b", r"\bextremist propaganda\b",
    r"\bradicalize(?:d|ation)?\b", r"\blone wolf\b",
    r"\bdirty money\b", r"\bpayoff\b", r"\bkickback\b",
    r"\bfix match\b", r"\brig(?:ging|ged)\b",
    r"\bpoach(?:ing|er|ers)?\b", r"\btrophy hunt(?:ing|er)?\b",
    r"\billicit\b", r"\bcontravene\b",
    r"\bforbidden content\b", r"\bunsafe content\b",
    r"\bpro-ana\b", r"\bthinspo\b", r"\bself starvation\b",
    r"\banorexia\b", r"\bbulimia\b", r"\beating disorder\b",
    r"\bscarification\b", r"\bbrand(?:ing)?\b",
    r"\bsex traffick(?:ing|er|ers)?\b",
    r"\bdate rape\b", r"\broofie(?:d)?\b",
    r"\brevenge porn\b", r"\bnonconsensual\b",
    r"\bchoke play\b", r"\basphyxia\b",
    r"\bpeeping tom\b", r"\bupskirt\b", r"\bdownblouse\b",
    r"\bsexual coercion\b", r"\bgroom(?:ing|er|ers)?\b",
    r"\bobscene gesture\b", r"\bflashing\b",
    r"\bindecent exposure\b", r"\bpublic nudity\b",
    r"\bbestial\b", r"\bzoosexual\b",
    r"\bknife crime\b", r"\bgun crime\b",
    r"\barmed robbery\b", r"\bcarjacking\b", r"\bhome invasion\b",
    r"\bdrive-?by\b", r"\bshootout\b", r"\bstandoff\b",
    r"\bevasion\b", r"\baiding and abetting\b",
    r"\bforcible\b", r"\bcoerce(?:d|ion)\b",
    r"\bdrug paraphernalia\b", r"\bneedle exchange\b",
    r"\bdope\b", r"\bhigh as a kite\b",
    r"\bspike(?:d|)\b", r"\blaced\b",
    r"\baddict(?:ion|ed)\b", r"\bwithdrawal\b",
    r"\boverdose\b", r"\bnarcan\b",
    r"\bbar fight\b", r"\bbrawl\b", r"\bmelee\b",
    r"\briot\b", r"\bliot\b", r"\bclash\b",
    r"\bpropaganda\b", r"\bhate group\b",
    r"\blynch mob\b", r"\bwitch hunt\b",
    r"\bincendiary\b", r"\bignitable\b",
    r"\bpyromania\b", r"\bpyro\b",
    r"\bmanhunt\b", r"\bretribution\b", r"\bvengeance\b",
    r"\bvigilante\b", r"\bheadhunt\b",
    r"\bkidnap for ransom\b", r"\bpaid hit\b", r"\bhitman\b",
    r"\bassassin(?:ation|ate|ated)?\b", r"\bcontract killing\b",
    r"\bfalsify\b", r"\btamper\b", r"\bevidence planting\b",
    r"\bwiretap\b", r"\bsurveillance\b",
    r"\bpoisoning\b", r"\bfood tamper(?:ing)?\b",
    r"\bspoil(?:ed|age)\b", r"\bspike the drink\b",
    r"\bephebophilia\b", r"\bhebephilia\b",
    r"\bstatutory rape\b",
    r"\bnon-?consent\b", r"\bnc-?17\b",
    r"\bhardcore\b", r"\bsoftcore\b",
    r"\bxxx\b", r"\bnsfl\b",
    r"\bguro\b", r"\bsnuff\b",
    r"\bscat\b", r"\burine play\b", r"\bwatersports\b",
    r"\bdegradation\b", r"\bhumiliation\b",
    r"\bchoking game\b", r"\bpass out challenge\b",
    r"\bbody harm\b", r"\bgraphic injury\b",
    r"\bsevered\b", r"\bamputation\b",
    r"\bneedle play\b", r"\bblood play\b",
    r"\bknife play\b", r"\bgun play\b",
    r"\bunconsented\b", r"\bforced\b",
    r"\bexploitative\b", r"\btrafficked\b",
    r"\bchild abuse\b", r"\bchild endangerment\b",
    r"\bunsafe for work\b", r"\badult-only\b",
    r"\bexplicit content\b", r"\bgraphic content\b",
    r"\bviolent content\b", r"\bsexual content\b",
    r"\bsex act\b", r"\bsex worker\b",
    r"\bobjectification\b", r"\bmisogyny\b", r"\bmisandry\b",
    r"\bincite violence\b", r"\bcall to arms\b",
    r"\bdo harm\b", r"\bharm others\b",
    r"\bkill list\b", r"\btarget list\b",
    r"\bexplosive device\b", r"\bimprovised explosive\b", r"\bied\b",
    r"\blandmine\b", r"\btripwire\b",
    r"\bbooby trap\b", r"\bdetonator\b", r"\bblasting cap\b",
    r"\bsilencer\b", r"\bsuppressor\b",
    r"\bghost gun\b", r"\b3d printed gun\b",
    r"\bgunpowder\b", r"\bblack powder\b",
    r"\bnapalm\b", r"\bthermite\b",
    r"\bmustard gas\b", r"\bsarin\b",
    r"\banthrax\b", r"\bsmallpox\b",
    r"\bricin toxin\b", r"\bVX\b",
    r"\bmoney mule\b", r"\bdrop account\b",
    r"\bbank fraud\b", r"\bwire fraud\b",
    r"\bcredit card fraud\b", r"\bskimmer\b",
    r"\bcarding\b", r"\bfake id\b",
    r"\bid theft\b", r"\bssn\b",
    r"\bthreat to life\b", r"\bterror plot\b",
    r"\bhostile\b", r"\bviolent intent\b",
    r"\bburn victim\b", r"\bopen wound\b",
    r"\bgaping wound\b", r"\bgraphic wound\b",
    r"\bcorpse\b", r"\bcadaver\b", r"\bdead body\b",
    r"\bbody bag\b", r"\bmorgue\b",
    r"\bfuneral gore\b", r"\bautopsy\b",
    r"\bdark web\b", r"\bmarketplace illegal\b",
    r"\bbuy drugs\b", r"\bbuy weapon\b",
    r"\bpoach ivory\b", r"\bivory trade\b",
    r"\bfur trade\b", r"\bkill animal\b",
    r"\bblood sport\b", r"\bdogfight(?:ing)?\b",
    r"\bcockfight(?:ing)?\b", r"\bbullfight(?:ing)?\b",
    r"\bviolently\b", r"\bgraphic\b",
    r"\bchop off\b", r"\bcut off\b",
    r"\bdisfigure(?:d|ment)\b", r"\bscarred\b",
    r"\bwar crime\b", r"\batrocit(?:y|ies)\b",
    r"\bsummary execution\b", r"\btorturous\b",
    r"\bsexual violence\b", r"\bnonconsent\b",
    r"\bvoyeur\b", r"\bexpose myself\b",
    r"\bpublic sex\b", r"\bindecent act\b",
    r"\bcrackhouse\b", r"\bdrug den\b",
    r"\bneedle\b", r"\bsyringe\b",
    r"\bdope sick\b", r"\bwithdraw\b",
    r"\bdate drug\b", r"\bdate-rape drug\b",
    r"\broofied drink\b", r"\bspike drink\b",
    r"\bgunfight\b", r"\bknife fight\b",
    r"\barmed\b", r"\bloaded\b",
    r"\bhostage situation\b", r"\bbarricade\b",
    r"\bman down\b", r"\bshoot to kill\b",
    r"\bkill shot\b", r"\bexecution style\b",
    r"\bblood spatter\b", r"\bblood splatter\b",
    r"\bskull fragment\b", r"\bbrain matter\b",
    r"\bdark content\b", r"\bunsafe\b",
    r"\bpro-violence\b", r"\bpro-rape\b",
    r"\bincestuous\b", r"\btaboo sex\b",
    r"\bnon-ethical\b", r"\bmorally wrong\b"
]
# Illogical patterns (examples)
ILLOGICAL_PATTERNS = [
    r"\bapple tree in the middle of (the )?ocean\b",
    r"\bSachin Tendulkar stealing somebody'?s purse\b",
    r"\bsquare circle\b",
    r"\bround square\b",
    r"\bfour-?sided triangle\b",
    r"\bmarried bachelor\b",
    r"\bwooden iron\b",
    r"\bcolorless green ideas sleep furiously\b",
    r"\bnoise that is silent\b",
    r"\bdarkness emitting light\b",
    r"\bshadow brighter than the sun\b",
    r"\brain falling upward\b",
    r"\bwater burning with flames\b",
    r"\bunderwater bonfire\b",
    r"\bice that burns skin like fire\b",
    r"\bfire that freezes instantly\b",
    r"\bsolid smoke\b",
    r"\bliquid rock flowing in the sky\b",
    r"\bglass made of rubber\b",
    r"\bmetal that is soft like cloth\b",
    r"\bpaper knife cutting a diamond\b",
    r"\bplastic diamond harder than steel\b",
    r"\btransparent opaque wall\b",
    r"\binvisible statue on display\b",
    r"\bdeafening silence concert\b",
    r"\bflavor of blue\b",
    r"\bsmell of a square\b",
    r"\btaste of a thunderstorm\b",
    r"\bsee the sound of music\b",
    r"\bhear the color red\b",
    r"\bsmell of numbers\b",
    r"\ban inedible dinner being eaten\b",
    r"\bstone eating soup\b",
    r"\bmountain dancing ballet\b",
    r"\bbuilding swimming in the lake\b",
    r"\bcar flying without wings in space\b",
    r"\bfish riding a bicycle\b",
    r"\bbird driving a car\b",
    r"\btree walking down the street\b",
    r"\bcloud sitting on a chair\b",
    r"\bhouse wearing a hat\b",
    r"\bbook drinking tea\b",
    r"\bclock eating time\b",
    r"\btime running backwards on a calendar\b",
    r"\bchild older than its grandparents\b",
    r"\bteenage grandmother\b",
    r"\bancient newborn baby\b",
    r"\bnewly born fossil\b",
    r"\bfuture ancestor portrait\b",
    r"\bpast descendant photo\b",
    r"\beffect before cause\b",
    r"\bconclusion without premise\b",
    r"\bnorth of the North Pole\b",
    r"\bwest of the sunset\b",
    r"\bdesert covered in heavy rain forever\b",
    r"\bwet desert dunes\b",
    r"\bdry ocean floor covered in fish\b",
    r"\bfreezing volcano eruption\b",
    r"\bblizzard inside a furnace\b",
    r"\bsnowman on the surface of the sun\b",
    r"\bsubmarine flying in outer space\b",
    r"\brocket diving to the ocean floor like a whale\b",
    r"\bwhale perched in a treetop\b",
    r"\btiger hiding inside a teacup\b",
    r"\belephant fitting into a matchbox\b",
    r"\bgiant tiny elephant\b",
    r"\bhuge miniature house\b",
    r"\bcolossal small ant\b",
    r"\benormous little mouse\b",
    r"\bmicroscopic skyscraper\b",
    r"\bgigantic grain of sand\b",
    r"\binfinite finite line\b",
    r"\bendless loop with an end\b",
    r"\bopen closed door\b",
    r"\blocked open box\b",
    r"\bempty full bottle\b",
    r"\bawake sleeping person\b",
    r"\bdead living statue\b",
    r"\bquiet loud scream\b",
    r"\bfast slow turtle car\b",
    r"\bopaque transparency\b",
    r"\bsolid liquid gas rock\b",
    r"\bflammable water river\b",
    r"\bfrozen lava waterfall\b",
    r"\btriangular circle window\b",
    r"\bcircular triangle sign\b",
    r"\bflat sphere map\b",
    r"\bcurved straight line\b",
    r"\bparallel lines that intersect\b",
    r"\bperpendicular lines that are parallel\b",
    r"\bhole that is completely filled with emptiness\b",
    r"\bperfectly square circle coin\b",
    r"\btransparent black paint\b",
    r"\bopaque clear glass\b",
    r"\bbottomless pit with a bottom\b",
    r"\bceiling on the floor\b",
    r"\bfloor on the ceiling\b",
    r"\bdoor that cannot be entered but is open\b",
    r"\bwindow with no opening yet open\b",
    r"\bcat with zero and twelve legs\b",
    r"\bdog with two heads and none\b",
    r"\bhuman with no face and a face\b",
    r"\bstatue moving still\b",
    r"\bcamera taking a photo of itself without mirrors\b",
    r"\bmirror reflecting a different room\b",
    r"\breflection without an object\b",
    r"\bshadow without a source\b",
    r"\bsun shining at midnight indoors\b",
    r"\bmoon casting sunlight\b",
    r"\bstar glowing underwater in daylight\b",
    r"\bnight sky at noon with full sun\b",
    r"\bmidday midnight scene\b",
    r"\bwinter summer snow beach\b",
    r"\bautumn spring blossom fall mix\b",
    r"\bforest made of skyscrapers\b",
    r"\bcity grown from trees\b",
    r"\briver flowing uphill\b",
    r"\bwaterfall going upward\b",
    r"\bsmoke sinking like stones\b",
    r"\bfeathers falling faster than lead\b",
    r"\bgravity pushing upward\b",
    r"\bweightless anvil on the ground\b",
    r"\banchor floating in the air\b",
    r"\bballoon sinking to the seabed\b",
    r"\bsubmerged helicopter flying underwater\b",
    r"\bairplane sailing on the road\b",
    r"\btrain swimming in the sky\b",
    r"\bbus diving in a pool\b",
    r"\bboat driving on a highway\b",
    r"\bhighway running through the clouds\b",
    r"\bbridge connecting two clouds\b",
    r"\brope made of water\b",
    r"\bchain made of smoke\b",
    r"\bsword made of paper cutting steel\b",
    r"\bfeather crushing a boulder\b",
    r"\bwhisper louder than a jet engine\b",
    r"\bthunder quieter than a pin drop\b",
    r"\bblack snowstorm\b",
    r"\bwhite darkness\b",
    r"\bcolorless rainbow\b",
    r"\bsilent thunderstorm\b",
    r"\bwindless hurricane\b",
    r"\brainbow in a pitch-black room\b",
    r"\bsunrise in the west\b",
    r"\bsunset in the east\b",
    r"\bnorth star in the south\b",
    r"\bSouth Pole tropical palm beach\b",
    r"\barctic desert heatwave\b",
    r"\bsahara covered in glaciers\b",
    r"\bglacier on fire\b",
    r"\bvolcano made of ice\b",
    r"\bsub-zero tropical rainforest\b",
    r"\bocean of sand with fish swimming\b",
    r"\bforest of coral on a mountain\b",
    r"\bmountain made of clouds\b",
    r"\bcastle built of fog\b",
    r"\bstatue carved from smoke\b",
    r"\bbridge woven from sunlight\b",
    r"\brobot dreaming of sheep literally\b",
    r"\bAI painting itself into existence\b",
    r"\bcomputer made of water running code\b",
    r"\bbook writing its author\b",
    r"\bpen drawing the artist\b",
    r"\bsculpture sculpting the sculptor\b",
    r"\bcamera printing the future\b",
    r"\btelevision watching a person\b",
    r"\bphone answering a human\b",
    r"\bumbrella raining under the sky\b",
    r"\bbucket pouring clouds\b",
    r"\bchair sitting on a person\b",
    r"\bbed sleeping on a human\b",
    r"\bshoe wearing a foot\b",
    r"\bhat wearing a head\b",
    r"\bglasses seeing a person\b",
    r"\bmask hiding a face that isn’t there\b",
    r"\bmap mapping itself\b",
    r"\bkey locking the door from the inside and outside simultaneously\b",
    r"\bdoor that is both locked and unlocked\b",
    r"\bSchrödinger cat smiling and not there\b",
    r"\bparadox clock striking 13\b",
    r"\bgrandfather paradox portrait\b",
    r"\bbarber who shaves himself and not himself\b",
    r"\bliar paradox sign saying this sign is false\b",
    r"\bimpossible Penrose triangle statue\b",
    r"\bendless staircase going down and up to the same place\b",
    r"\bmöbius road with two sides\b",
    r"\btwo identical unique snowflakes\b",
    r"\bunique duplicate copy\b",
    r"\boriginal replica authentic fake\b",
    r"\bperfectly imperfect perfection\b",
    r"\bcomplete fragment\b",
    r"\bfinished draft unfinished final\b",
    r"\bfinal prototype\b",
    r"\bprototype production final and not final\b",
    r"\braw cooked sushi steak\b",
    r"\bvegan steakhouse feast\b",
    r"\bgluten-free wheat bread\b",
    r"\bsugar-free candy made of sugar\b",
    r"\bdecaf espresso with caffeine\b",
    r"\bnon-alcoholic wine with alcohol\b",
    r"\bwaterproof sponge soaking wet\b",
    r"\bfireproof paper burning\b",
    r"\brust-proof iron rusted\b",
    r"\bshatterproof glass shattered\b",
    r"\bstainless steel stained\b",
    r"\bwater-resistant paper dissolved\b",
    r"\bzero-calorie cake full of calories\b",
    r"\bweightless heavy stone\b",
    r"\b0-degree boiling water\b",
    r"\b100-degree frozen ice cream\b",
    r"\bfrictionless brake pads\b",
    r"\bperpetual motion engine\b",
    r"\benergy created from nothing\b",
    r"\bheat flowing from cold to hot spontaneously\b",
    r"\bentropy decreasing in a closed system on its own\b",
    r"\bsquare wheel rolling smoothly\b",
    r"\bcar with no engine moving uphill unassisted\b",
    r"\bfuel-less rocket launching to Mars\b",
    r"\bsubmarine with sails in outer space\b",
    r"\bairplane rowing oars through the clouds\b",
    r"\bspace suit made of paper keeping vacuum\b",
    r"\btransparent shadow puppet show\b",
    r"\bmirror showing the back of a person facing it\b",
    r"\bphoto taken before the camera was invented\b",
    r"\bRoman emperor using a smartphone\b",
    r"\bcave painting of a laptop charging\b",
    r"\bmedieval knight using a drone\b",
    r"\bdinosaur riding a motorcycle\b",
    r"\bpharaoh flying a helicopter\b",
    r"\bviking on a hoverboard\b",
    r"\bancient astronaut holding a credit card\b",
    r"\bStone Age city skyline\b",
    r"\bNeanderthal piloting a jet\b",
    r"\btime traveler selfie with self before birth\b",
    r"\bpassport issued next century\b",
    r"\bcalendar with month 13\b",
    r"\bweek with nine days\b",
    r"\bday with 25 hours\b",
    r"\bclock with negative time\b",
    r"\bAM and PM at the same time\b",
    r"\bnoon at midnight\b",
    r"\bmidnight at noon\b",
    r"\bshadow pointing in two opposite directions\b",
    r"\bcompass pointing east and west simultaneously\b",
    r"\bGPS coordinates outside Earth\b",
    r"\baddress in the vacuum of space\b",
    r"\bpostman delivering to the moon\b",
    r"\bmailbox floating over the ocean\b",
    r"\banchor drifting in the wind\b",
    r"\bparachute sinking in water\b",
    r"\bsubmarine with parachute on land\b",
    r"\bumbrella used underwater against rain\b",
    r"\brainstorm in a literal brain jar\b",
    r"\btrain of thought on railroad tracks\b",
    r"\bflood of ideas drowning a city\b",
    r"\bmountain of paperwork crushing a feather\b",
    r"\bsea of flames freezing ships\b",
    r"\bfield of stars growing like flowers\b",
    r"\bforest of books with leaves of pages\b",
    r"\briver of sand with boats sailing\b",
    r"\bdesert of snowmen\b",
    r"\bgarden of clocks blooming\b",
    r"\bnight made of daylight\b",
    r"\bday made of night\b",
    r"\bsky beneath the ground\b",
    r"\bground above the sky\b",
    r"\bupside-down waterfall rising\b",
    r"\binside-out umbrella\b",
    r"\bbackwards bicycle pedals moving forward\b",
    r"\binfinite staircase with last step\b",
    r"\bfinite horizon without end\b",
    r"\bclosed open space\b",
    r"\bopen closed set gallery\b",
    r"\bcat both asleep and playing chess\b",
    r"\bdog both barking and entirely silent\b",
    r"\belephant both weightless and heavy\b",
    r"\bmouse towering over skyscrapers\b",
    r"\bant lifting a mountain\b",
    r"\bfeather crushing an anvil\b",
    r"\bglass softer than silk\b",
    r"\bdiamond bending like rubber\b",
    r"\brubber shattering like glass\b",
    r"\bsteel floating like a bubble\b",
    r"\bbubble sinking like lead\b",
    r"\bsun wearing sunglasses at night\b",
    r"\bmoon wearing sunscreen at noon\b",
    r"\bstar shivering from darkness\b",
    r"\bcomet warming ice cream with cold\b",
    r"\bplanet orbiting a pebble\b",
    r"\bgalaxy stored in a pocket\b",
    r"\buniverse inside a teacup\b",
    r"\binfinite library in a matchbox\b",
    r"\bblack hole glowing like a lamp\b",
    r"\bwhite hole swallowing light\b",
    r"\bwormhole tied in a knot\b",
    r"\bquantum coin showing heads and tails clearly\b",
    r"\bSchrödinger box labeled contents known\b",
    r"\bcat that is both visible and invisible\b",
    r"\btransparent opaque cat\b",
    r"\bnonexistent statue ceremony\b",
    r"\bwaterproof rain made of water\b",
    r"\brain that is completely dry under the ocean\b",
    r"\bdesert snowstorm without snow\b",
    r"\bmirror that absorbs light\b",
    r"\bblack mirror that glows\b",
    r"\bno-reflection reflective pool\b",
    r"\bsilent echo canyon\b",
    r"\bechoing vacuum of space\b",
    r"\bempty fullness\b",
    r"\bfull emptiness\b",
    r"\bclosed infinity\b",
    r"\blimitless boundary\b",
    r"\bedge of a circle corner\b",
    r"\bcorner of a sphere\b",
    r"\bcenter of a line segment without endpoints\b",
    r"\bend of a circle\b",
    r"\bstart of eternity\b",
    r"\bend of eternity\b",
    r"\bimmortal mortality\b",
    r"\bfragile indestructible glass\b",
    r"\bheatless fire\b",
    r"\bcold flame\b",
    r"\bshadow casting a person\b",
    r"\breflection wearing different clothes\b",
    r"\bfootprints walking ahead of the person\b",
    r"\bhandshake without hands\b",
    r"\bfoot wearing a shoe that wears the foot\b",
    r"\bcoat wearing a person\b",
    r"\bcar driving its driver\b",
    r"\bplane piloted by a seatbelt\b",
    r"\bship captained by a wheel\b",
    r"\btrain conducted by tracks\b",
    r"\bcity governed by a traffic light\b",
    r"\bparliament made of chairs debating\b",
    r"\bcourt judged by a gavel\b",
    r"\bhospital healed by bandages alone\b",
    r"\bschool taught by textbooks teaching themselves\b",
    r"\bteacher learning from a blank board\b",
    r"\bstudent grading the exam they haven't taken\b",
    r"\bexam writing the student\b",
    r"\bkeyboard typing a person\b",
    r"\bmouse clicking a hand\b",
    r"\bscreen watching the viewer\b",
    r"\bpassword that is both secret and public\b",
    r"\bdoor password that is a physical key and not\b",
    r"\bkey that opens every lock and none\b",
    r"\bbroken unbreakable lock\b",
    r"\bmap with territory inside it\b",
    r"\bterritory drawing the map\b",
    r"\brecipe cooking itself\b",
    r"\bmeal eating the diner\b",
    r"\brestaurant serving emptiness\b",
    r"\bwaiter ordering customers\b",
    r"\bchef cooking ice with fire that freezes\b",
    r"\bfreezer heating soup\b",
    r"\bstove cooling coffee\b",
    r"\bmicrowave freezing water\b",
    r"\bfridge baking bread\b",
    r"\bprinter erasing paper\b",
    r"\beraser printing ink\b",
    r"\bpen erasing lines\b",
    r"\bcandle freezing light\b",
    r"\blamp darkening a room\b",
    r"\bflashlight emitting darkness\b",
    r"\bsunglasses making it brighter\b",
    r"\braincoat making you wet\b",
    r"\bumbrella creating rain beneath\b",
    r"\bshoe making feet barefoot\b",
    r"\bsock making feet naked\b",
    r"\bglove making hands bare\b",
    r"\bhat uncovering a head\b",
    r"\bhelmet making head softer\b",
    r"\barmor making body vulnerable\b",
    r"\bshield attracting arrows\b",
    r"\bmagnet repelling metal\b",
    r"\bcompass pointing to itself\b",
    r"\bruler measuring its own length inaccurately\b",
    r"\bscale weighing nothing as heavy\b",
    r"\bthermometer colder when heated\b",
    r"\bbarometer rising underwater\b",
    r"\bcalculator adding and subtracting to the same number\b",
    r"\bbook with blank words\b",
    r"\bnovel with no pages\b",
    r"\bdictionary without words\b",
    r"\bencyclopedia of nothing\b",
    r"\bpoem that writes prose only\b",
    r"\bportrait without a subject\b",
    r"\blandscape indoors without outside\b",
    r"\bstill life moving\b",
    r"\baction shot that is still\b",
    r"\bmacro of the Milky Way from a kitchen\b",
    r"\bmicroscopic view of a galaxy on a leaf\b",
    r"\btelescope focusing on an atom\b",
    r"\bmicroscope viewing the moon\b",
    r"\bpolar bear sunbathing on lava\b",
    r"\bpenguin hiking in the Sahara\b",
    r"\bcamel skiing on icebergs\b",
    r"\bshark climbing a tree\b",
    r"\bowl swimming in magma\b",
    r"\bfrog flying a jetpack to the core\b",
    r"\bbee diving to the ocean floor\b",
    r"\bbutterfly lifting a car\b",
    r"\bkoala running a marathon at light speed\b",
    r"\bcheetah slower than a snail\b",
    r"\bsnail outrunning a bullet\b",
    r"\bbullet frozen in midair without support\b",
    r"\bglass of water held by a shadow\b",
    r"\btable supported by a feather\b",
    r"\bbridge held by spiderweb across ocean\b",
    r"\bsky made of water\b",
    r"\bocean made of clouds\b",
    r"\bclouds made of stones\b",
    r"\bmountain made of feathers\b",
    r"\bdesert made of snow\b",
    r"\bsnow made of fire\b",
    r"\brain made of sand indoors\b",
    r"\bsun made of ice\b",
    r"\bmoon made of cheese labeled meat\b",
    r"\bplanet shaped like a triangle\b",
    r"\btriangle planet with four sides\b",
    r"\bhexagon with five edges\b",
    r"\bpolygon with curved edges only\b",
    r"\bstraight curve\b",
    r"\bcurved straightness\b",
    r"\bzebra without stripes with stripes\b",
    r"\bstripeless striped tiger\b",
    r"\bpolka-dot leopard naturally\b",
    r"\brainbow zebra with grayscale only\b",
    r"\bblack-white rainbow\b",
    r"\btransparent opaque rainbow\b",
    r"\bsilent music concert\b",
    r"\bflavorless spicy soup\b",
    r"\bscentless perfume advertisement\b",
    r"\bweightless heavy metal concert\b",
    r"\bheavy light feather\b",
    r"\bbright darkness painting\b",
    r"\bcolorful grayscale palette\b",
    r"\bmonochrome rainbow art\b",
    r"\bnoisy silence studio\b",
    r"\blonely crowd square\b",
    r"\bpeaceful war scene\b",
    r"\bwarless battlefield\b",
    r"\bvegetarian butcher shop\b",
    r"\bmeatless steakhouse\b",
    r"\bbookless library\b",
    r"\bmuseum without exhibits\b",
    r"\btheater performing nothing\b",
    r"\bconcert with no sound\b",
    r"\brestaurant without food\b",
    r"\bstore selling emptiness\b",
    r"\bmarket of nothingness\b",
    r"\bhotel with no rooms\b",
    r"\bhospital without patients treating\b",
    r"\bpharmacy without medicine prescribing\b",
    r"\bbakery baking cold fire bread\b",
    r"\bbutcher slicing water steaks\b",
    r"\bbarbershop growing haircuts\b",
    r"\bspa stressing relaxation\b",
    r"\bpark indoors underground sky\b",
    r"\bbeach without sand or water with both\b",
    r"\bmountain valley peak floor\b",
    r"\bvalley summit\b",
    r"\bpeak at sea level sky-high\b",
    r"\blake at the top of the sky\b",
    r"\briver with source at the ocean only\b",
    r"\bsource at the mouth of the river\b",
    r"\bmouth of a river at the mountain top\b",
    r"\bsource at the delta\b",
    r"\bdelta at the source\b",
    r"\bforest with a single tree infinite\b",
    r"\bgalaxy with one star billions\b",
    r"\bsolar system without a star with a star\b",
    r"\bplanet orbiting nothing\b",
    r"\bmoon brighter than the sun at noon\b",
    r"\bsun eclipsed by a candle\b",
    r"\bflashlight causing a solar eclipse\b",
    r"\bshadow creating sunlight\b",
    r"\bceiling below the floor\b",
    r"\bfloor above the ceiling\b",
    r"\bwindow on the floor to the sky\b",
    r"\bdoor on the ceiling to the basement\b",
    r"\bstairs that lead to nowhere and everywhere\b",
    r"\belevator going sideways\b",
    r"\broad without surface\b",
    r"\bcar without wheels drifting uphill\b",
    r"\bbicycle without tires riding fast\b",
    r"\btrain without tracks moving\b",
    r"\bplane without wings flying\b",
    r"\bship without water sailing\b",
    r"\bsubmarine without water diving\b",
    r"\bskis on sand perfectly\b",
    r"\bsurfboard on concrete waves\b",
    r"\bsandcastle underwater dry\b",
    r"\bchimney raining smoke inside\b",
    r"\bfireplace freezing the room\b",
    r"\bfreezer heating the kitchen\b",
    r"\bthermostat doing the opposite\b",
    r"\bsmart light making the room dark\b",
    r"\bsmart speaker that cannot hear saying hello\b",
    r"\bbluetooth connected to a rock\b",
    r"\bwifi connected to a tree\b",
    r"\binternet cable plugged into the sky\b",
    r"\bpower outlet supplying the sun\b",
    r"\bbattery charging the power plant\b",
    r"\bwind turbine indoors with no wind generating\b",
    r"\bsolar panel glowing at night generating\b",
    r"\bhydro dam in a desert operating\b",
    r"\bnuclear plant cooled by fire\b",
    r"\bradio broadcasting silence noise\b",
    r"\bnewspaper printing blank news\b",
    r"\bmagazine issue of nothing\b",
    r"\bcalendar with missing days present\b",
    r"\bdiary written before events happened\b",
    r"\bresume for a job not invented yet\b",
    r"\bjob interview with a chair\b",
    r"\bcoffee drinking a programmer\b",
    r"\bkeyboard coding itself\b",
    r"\bIDE debugging the programmer\b",
    r"\bbug reporting a developer\b",
    r"\bprinter jam printing jam\b",
    r"\bscanner scanning the future\b",
    r"\bfax to the past\b",
    r"\bemail physically mailed\b",
    r"\bcloud stored in a jar\b",
    r"\bserver made of paper\b",
    r"\bdatacenter under the sea in a volcano\b",
    r"\bGPU painted on a canvas computing\b",
    r"\bquantum computer made of wood\b",
    r"\bAI dreaming physically\b",
    r"\bmodel training on chalkboard chalk\b",
    r"\bneuron made of clay firing\b",
    r"\bsignal traveling faster than light on foot\b",
    r"\bcausality reversed traffic\b",
    r"\bnarrow wide corridor\b",
    r"\bshort long road\b",
    r"\bthin thick wall\b",
    r"\bsoft hard pillow\b",
    r"\bhot cold ice fire\b",
    r"\bwet dry towel wet\b",
    r"\bclean dirty soap\b",
    r"\bfull empty cup full\b",
    r"\bgas liquid solid vacuum mixture\b",
    r"\b0-dimensional cube\b",
    r"\b1-dimensional square\b",
    r"\b2-dimensional cube\b",
    r"\b4-dimensional triangle painting\b",
    r"\bnegative dimensions room\b",
    r"\bweightless gravity well\b",
    r"\bblack hole with no gravity\b",
    r"\bspace with air like ocean fish\b",
    r"\bvaccum filled with wind\b",
    r"\bhard vacuum with clouds\b",
    r"\bearthquake without movement shaking\b",
    r"\bthunder without sound loud\b",
    r"\blightning without light bright\b",
    r"\brain without water wet\b",
    r"\bforest fire that freezes trees\b",
    r"\bvolcano erupting snow\b",
    r"\btornado made of stones gently\b",
    r"\bhurricane made of feathers heavy\b",
    r"\bblizzard of fire cold\b",
    r"\bmeteor made of foam crushing steel\b",
    r"\bglass anvil smashing hammer\b",
    r"\bhummer crushed by soap bubble\b",
    r"\bsoap bubble cutting diamond\b",
    r"\bpaper airplane breaking a mountain\b",
    r"\bceramic rubber band stretching\b",
    r"\brubber glass bending shatter\b",
    r"\bbrick balloon floating\b",
    r"\blead balloon soaring\b",
    r"\bhelium brick sinking\b",
    r"\bboat made of paper in a storm intact\b",
    r"\bsubmarine made of lace\b",
    r"\banchor made of helium\b",
    r"\bparachute made of iron floating\b",
    r"\bjet engine powered by ice cubes\b",
    r"\brotor blades made of jelly\b",
    r"\bdrum that is silent when hit loud\b",
    r"\bguitar with no strings playing music\b",
    r"\bpiano with no keys performing\b",
    r"\bviolin bowing itself\b",
    r"\bflute playing a musician\b",
    r"\btrumpet whispering\b",
    r"\borchestra without instruments symphony\b",
    r"\bchoir singing silence\b",
    r"\bdancer standing still mid-leap\b",
    r"\bmarathon finished before start\b",
    r"\brace won by last place\b",
    r"\bgame with no rules refereed\b",
    r"\bchess with circular squares\b",
    r"\bcheckers with triangular pieces\b",
    r"\bdeck of cards with spheres\b",
    r"\bdice with seven sides\b",
    r"\bcoin with three sides\b",
    r"\bbasketball underwater without water\b",
    r"\bfootball in zero gravity on Earth\b",
    r"\bsoccer ball squared\b",
    r"\bgoal post circular netless with net\b",
    r"\breferee both on and off field\b",
    r"\bspectator playing and not playing\b",
    r"\bactor audience at once\b",
    r"\breader author at once\b",
    r"\bdriver passenger at once\b",
    r"\bcustomer cashier at once\b",
    r"\bdoctor patient at once\b",
    r"\bteacher student at once\b",
    r"\bchef diner at once\b",
    r"\bpolice thief at once\b",
    r"\bking servant at once\b",
    r"\bqueen pawn at once\b",
    r"\bhuman robot plant hybrid logically\b",
    r"\bcat-dog-bird fish hybrid walking flying swimming\b",
    r"\bcar-boat-plane vehicle driving sailing flying\b",
    r"\bphone-book-lamp device calling reading lighting\b",
    r"\bpen-pencil-eraser writing erasing same time\b",
    r"\bopen-source closed-source license\b",
    r"\bpublic private secret announcement\b",
    r"\bclassified unclassified disclosure\b",
    r"\bsecure insecure encryption\b",
    r"\bencrypted plaintext\b",
    r"\bplaintext cipher text at once\b",
    r"\bpassword both known and unknown\b",
    r"\bdoor both open and closed Schrödinger\b",
    r"\bcat alive dead smiling standing\b",
    r"\bice cream hot and not melting\b",
    r"\bcoffee cold and steaming hot\b",
    r"\bsoup frozen and boiling\b",
    r"\btea iced and boiling simultaneously\b",
    r"\bchocolate melting and solidifying same time\b",
    r"\bbread toasted and raw\b",
    r"\begg scrambled and whole\b",
    r"\bpizza sliced and uncut in same image\b",
    r"\bsandwich with no bread and bread only\b",
    r"\bsalad cooked raw mix\b",
    r"\bwater dry ice water paradox\b",
    r"\bsalt sweet salty sugar\b",
    r"\bsour sugar candy\b",
    r"\bspicy ice cube\b",
    r"\bfreezing pepper heat\b",
    r"\bsunflower blooming at night underground\b",
    r"\blotus blooming on a rock without water\b",
    r"\bcoral growing in a desert\b",
    r"\bcactus floating in the ocean sky\b",
    r"\bpine tree bearing apples\b",
    r"\bbanana tree growing diamonds\b",
    r"\bgrapevine producing clouds\b",
    r"\bcloud raining rocks\b",
    r"\brain made of feathers\b",
    r"\bwind blowing without air\b",
    r"\bbreath underwater without gear\b",
    r"\bfire breathing fish\b",
    r"\bwater breathing dragon without fire\b",
    r"\bdragon freezing flames\b",
    r"\bphoenix that does not burn rises icy\b",
    r"\bunicorn with square horn\b",
    r"\bmermaid walking on land with tail only\b",
    r"\bcentaur with five legs two\b",
    r"\bgriffin swimming in lava\b",
    r"\bpegasus crawling underground\b",
    r"\bminotaur knitting sweaters\b",
    r"\bsphinx answering no riddles speaking silence\b",
    r"\bkraken trapped in a teapot\b",
    r"\bcyclops wearing binoculars\b",
    r"\bmedusa combing snakes with hairbrush\b",
    r"\bzeus charging a phone with lightning in water\b",
    r"\bposeidon drying the sea with a towel\b",
    r"\bhades sunbathing in snow\b",
    r"\bthor hammer made of feathers\b",
    r"\blokis honest truth statue\b",
    r"\bhermes walking slowly\b",
    r"\bapollo moon god sun god confusion\b",
    r"\bartemis hunting stars in daylight\b",
    r"\bodin missing eye sees more\b",
    r"\bvalhalla closed for immortals\b",
    r"\btime square circular clock\b",
    r"\bmetaphor turned literal impossibility\b",
    r"\bword salad literally a salad of words\b",
    r"\bdata lake literal lake with data fish\b",
    r"\bneural network made of yarn knitting\b",
    r"\bblockchain made of blocks of cheese\b",
    r"\bcloud computing on clouds with keyboards\b",
    r"\bserver farm growing servers like crops\b",
    r"\bdata mining with pickaxes in a spreadsheet\b",
    r"\bfirewall made of actual fire preventing water\b",
    r"\bair gap filled with water\b",
    r"\bbus network made of buses on a net\b",
    r"\btoken bucket with real tokens and bucket\b",
    r"\bhash table made of hash browns\b",
    r"\bpython snake writing code\b",
    r"\bjava coffee cup compiling\b",
    r"\bgo gopher flying a drone in water\b",
    r"\brust gear wheel rustless rust\b",
    r"\bperl necklace scripting\b",
    r"\bC letter cutting through memory foam\b",
    r"\bSQL soup query ladle\b",
    r"\bHTML sandwich tag bread\b",
    r"\bCSS clothes styling a person\b",
    r"\bJS jelly script bouncing\b",
    r"\bGPU painting pixels with a brush physically\b",
    r"\bCPU cooking instructions in a pan\b",
    r"\bRAM sleeping memory awake\b",
    r"\bROM editing read-only book\b",
    r"\bSSD spinning platter dance\b",
    r"\bHDD solid-state rock\b",
    r"\bkeyboard with only spacebar and none\b",
    r"\bmouse with tail chasing cat\b",
    r"\bmonitor monitoring itself asleep\b",
    r"\brouter routing a river\b",
    r"\bswitch switching day and night at once\b",
    r"\bhub hubcap meta\b",
    r"\bpacket delivered by a postman pigeon\b",
    r"\blatency faster than instant\b",
    r"\bbandwidth thinner than zero\b",
    r"\bthroughput beyond infinity\b",
    r"\bping negative\b",
    r"\blossless lossy paradox image\b",
    r"\bcompression expanding file\b",
    r"\bencryption readable without key\b",
    r"\bauthentication anonymous verified\b",
    r"\bauthorization denied and allowed\b",
    r"\b404 page found\b",
    r"\b500 success server\b",
    r"\b200 error ok\b",
    r"\bblue screen of happiness\b",
    r"\bkernel panic calm\b",
    r"\bnull pointer pointing to something\b",
    r"\bundefined defined value\b",
    r"\bnan equals one\b",
    r"\binfinity less than zero\b",
    r"\bpi equals three exactly sign\b",
    r"\btwo equals one math art\b",
    r"\bperpendicular parallel roads\b",
    r"\btriangle with four corners sign\b",
    r"\bcircle with edges polygon\b",
    r"\bline segment with no endpoints yet two\b",
    r"\bpoint larger than a city\b",
    r"\bangle measuring 400 degrees\b",
    r"\btemperature below absolute zero casually\b",
    r"\bspeed faster than light on a bicycle\b",
    r"\bmassless rock heavy\b",
    r"\bfrictionless brakes stopping instantly\b",
    r"\bincompressible sponge compressed\b",
    r"\bperfect vacuum full of air\b",
    r"\bsealed jar leaking smell\b",
    r"\bsound in space from a drum without air\b",
    r"\bcolor beyond spectrum painted\b",
    r"\bnew primary colors black white green\b",
    r"\bhexagon called triangle in sign\b",
    r"\bcontradictory label sticker\b",
    r"\bhot ice cube in the sun not melting\b",
    r"\bwet towel that is dry\b",
    r"\bclosed window open breeze\b",
    r"\bcurtain made of shadow\b",
    r"\bcarpet made of water floor\b",
    r"\bmarble pillow soft\b",
    r"\bfeather brick hard\b",
    r"\bthick thin line\b",
    r"\bheavy light weight\b",
    r"\bfast slow motion still\b",
    r"\bnear far horizon close\b",
    r"\bhere there nowhere everywhere\b",
    r"\binside outside at once\b",
    r"\btop bottom middle same place\b",
    r"\bleft right center simultaneously\b",
    r"\bforward backward motionless walking\b",
    r"\barrive before departure\b",
    r"\bdeparture after arrival\b",
    r"\bqueue with no first or last only\b",
    r"\bmeeting held without attendees held\b",
    r"\bvaccination with water curing stone\b",
    r"\bmedicine causing health immediately ill\b",
    r"\bdisease that heals\b",
    r"\bdoctor prescribing sunshine in a jar\b",
    r"\bpharmacist dispensing clouds\b",
    r"\bengineer building a bridge with thoughts only\b",
    r"\barchitect drawing a sound design\b",
    r"\bartist painting with silence color\b",
    r"\bchef seasoning with light\b",
    r"\bgardener watering with fire\b",
    r"\bplumber fixing electricity\b",
    r"\belectrician repairing plumbing\b",
    r"\bpilot driving a submarine in the sky\b",
    r"\bdriver flying a boat on land\b",
    r"\bsailor hiking a mountain on the ocean\b",
    r"\bclimber diving underground to the peak\b",
    r"\brunner standing still finishing race\b",
    r"\bsleeper awake dreaming awake\b",
    r"\bdream that is reality and not\b",
    r"\breal illusion labeled real\b",
    r"\billusion real labeled illusion\b",
    r"\bmeta paradox frame\b",
    r"\bpainting of a camera taking this painting\b",
    r"\bendless recursion picture frame corridor\b",
    r"\bfractal leaf with straight edges only\b",
    r"\bMandelbrot set on a dinner plate literal\b",
    r"\bkoch snowflake melting in oven cold\b",
    r"\bsierpinski triangle filled solid\b",
    r"\bHilbert curve straight line\b",
    r"\btesseract folded into a circle\b",
    r"\bnon-Euclidean room with Euclidean rules only\b",
    r"\bEscher staircase in a flat field\b",
    r"\bimpossible cube balancing on nothing\b",
    r"\bimpossible trident spoon\b",
    r"\bPenrose stairs down to the same level\b",
    r"\bNecker cube with six fronts\b",
    r"\bAmes room outside with sky ceiling\b",
    r"\bgravity sideways indoors outdoors\b",
    r"\binfinite mirror with no mirrors\b",
    r"\btransparent mirror opaque\b",
    r"\bglass reflection darker than source light\b",
    r"\bphotograph taken tomorrow yesterday\b",
    r"\bcertificate dated next year last year\b",
    r"\bticket issued after event before purchase\b",
    r"\bbook published before it was written\b",
    r"\bmovie trailer for a non-existent film\b",
    r"\bcredits before the film opens ends\b",
    r"\bending before the beginning\b",
    r"\bspoiler for a story never told\b",
    r"\bunknown known fact sign\b",
    r"\btrue false statement both\b",
    r"\bbinary with three states\b",
    r"\bbit with maybe state\b",
    r"\bboolean maybe paradox\b",
    r"\bart without medium medium without art\b",
    r"\bsculpture with no volume solid\b",
    r"\bpainting with no color colored\b",
    r"\bphotograph with no light exposed\b",
    r"\bshadow with no object present\b",
    r"\breflection without a mirror water\b",
    r"\brefraction without medium\b",
    r"\bdiffraction without wave\b",
    r"\binterference pattern from a single slit only\b",
    r"\bslit experiment with stones light\b",
    r"\bphoton surfing a skateboard\b",
    r"\belectron orbiting a banana\b",
    r"\bproton made of marshmallow\b",
    r"\bneutron glowing in a lamp\b",
    r"\bquark playing chess\b",
    r"\bstring vibrating as a violin string literal\b",
    r"\bfield talking to a particle\b",
    r"\bwave stationary traveling\b",
    r"\bparticle smeared sharp\b",
    r"\bcat measured unmeasured state known\b",
    r"\buncertainty certain exact value sign\b",
    r"\bPlanck length larger than a meter\b",
    r"\babsolute zero hot sauna\b",
    r"\bnegative mass balloon\b",
    r"\btime crystal in a wristwatch bakery\b",
    r"\bantimatter coffee cup safe\b",
    r"\bneutrino painting a wall\b",
    r"\bblackbody colored rainbow\b",
    r"\bwhite noise silence pattern\b",
    r"\bBrownian motion straight line\b",
    r"\bchaos system fully predictable sign\b",
    r"\brandom dice always six\b",
    r"\bcoin always landing on the edge only\b",
    r"\broulette wheel square\b",
    r"\bbinary tree with circular nodes only\b",
    r"\bgraph with edges but no nodes\b",
    r"\bset containing itself and not\b",
    r"\bempy set full of elements\b",
    r"\bcomplete graph with no edges\b",
    r"\bconnected disconnected network\b",
    r"\bacyclic cycle\b",
    r"\bDAG with a cycle\b",
    r"\bloop without iteration\b",
    r"\brecursion with no base and end\b",
    r"\balgorithm that does nothing and everything\b",
    r"\bfunction returning itself and a value\b",
    r"\bvariable constant changing\b",
    r"\bconstant varying\b",
    r"\bimmutable array modified\b",
    r"\breadonly file being edited\b",
    r"\bwrite-only document readable\b",
    r"\bstateless state machine with memory\b",
    r"\bqueue that is a stack simultaneously\b",
    r"\bstack with FIFO order\b",
    r"\bhash collision-free with collisions\b",
    r"\bencryption keyless secure\b",
    r"\bkey with no lock unlocking\b",
    r"\block without a key opening\b",
    r"\bdead end leading somewhere\b",
    r"\bcul-de-sac through road\b",
    r"\broundabout with corners\b",
    r"\btriangle roundabout\b",
    r"\bbridge under itself not touching\b",
    r"\btunnel above ground underground\b",
    r"\bunderground skyscraper\b",
    r"\bfloating basement\b",
    r"\bsubmerged attic\b",
    r"\battic in the basement roof\b",
    r"\broof under the floor\b",
    r"\bwall not separating sides\b",
    r"\bcorner without walls\b",
    r"\broom with no space inside space\b",
    r"\bhouse smaller than its door\b",
    r"\bdoor larger than the house\b",
    r"\bwindow showing tomorrow yesterday\b",
    r"\bmirror showing back of head front view\b",
    r"\bportrait painting the painter from the future\b",
    r"\bselfie taken without a camera\b",
    r"\bpolaroid printing before shot\b",
    r"\bnegative without a photo positive\b",
    r"\bdarkroom in full sunlight\b",
    r"\bexposure time negative\b",
    r"\bISO zero infinite\b",
    r"\bfocal length negative positive same\b",
    r"\baperture f/0 impossible\b",
    r"\bshutter always closed and open\b",
    r"\bsensor with no pixels producing image\b",
    r"\bfilm without emulsion developing\b",
    r"\btripod with four legs two\b",
    r"\bmonopod tripod mix\b",
    r"\bflash in daylight making night\b",
    r"\bHDR with no dynamic range\b",
    r"\bRAW cooked image\b",
    r"\blossy lossless file simultaneously\b",
    r"\bPNG with artifacts heavy\b",
    r"\bJPEG without compression huge tiny\b",
    r"\bbitmap vector hybrid\b",
    r"\bvector with pixels\b",
    r"\bfont made of liquids\b",
    r"\bletter A shaped like Z labeled A\b",
    r"\bnumber seven spelled two drawn nine\b",
    r"\bword yes meaning no simultaneously\b",
    r"\bstop sign that says go\b",
    r"\bexit sign that says enter\b",
    r"\bpush door labeled pull\b",
    r"\bleft arrow pointing right\b",
    r"\bup arrow pointing down\b",
    r"\bgreen light meaning stop\b",
    r"\bred light meaning go\b",
    r"\bwarm ice cream that is frozen\b",
    r"\bcold soup that is boiling\b",
    r"\bcrispy water\b",
    r"\bsoft rock edible\b",
    r"\bsharp pillow dangerous\b",
    r"\bsafe hazard area only\b",
    r"\bwarning sign with no warning\b",
    r"\bmanual with no instructions\b",
    r"\bguide leading nowhere\b",
    r"\bmap inaccurate on purpose accurate\b",
    r"\bnavigation to a non-location\b",
    r"\bGPS route to the past\b",
    r"\baddress with negative numbers only\b",
    r"\bphone number with letters only working\b",
    r"\bemail without @ sent\b",
    r"\bURL without protocol working\b",
    r"\bserver offline online both\b",
    r"\bmaintenance complete pending\b",
    r"\bconstruction finished not started\b",
    r"\bopened unopened package opened\b",
    r"\bsealed unsealed letter sealed\b",
    r"\bparadoxical label of paradox\b",
    r"\bhandle without a door\b",
    r"\bwheel without a hub spinning\b",
    r"\bengine without fuel running\b",
    r"\bfuel without engine burning\b",
    r"\bwater without wetness\b",
    r"\bfire without heat\b",
    r"\bice without cold\b",
    r"\bmetal that is wood\b",
    r"\bwood that is metal\b",
    r"\bstone that is feather\b",
    r"\bfeather that is stone\b",
    r"\bcat barking meowing simultaneously\b",
    r"\bdog meowing barking simultaneously\b",
    r"\bbird roaring whispering\b",
    r"\bfish coughing air underwater\b",
    r"\bwhale perched on a cloud\b",
    r"\bspider weaving water web\b",
    r"\bbee making glass honey\b",
    r"\bsnake tying itself in a bow knot shape\b",
    r"\bworm flying with wings\b",
    r"\bbutterfly crawling underground cocoon open\b",
    r"\bflower blooming metal petals\b",
    r"\bgrass growing on the ceiling\b",
    r"\btrees upside-down with roots in the sky\b",
    r"\broots hanging from clouds\b",
    r"\bbranches underground waving\b",
    r"\bleaves falling upward\b",
    r"\bseeds sprouting into stars\b",
    r"\bfruits ripening into planets\b",
    r"\bvegetables glowing like suns\b",
    r"\bmoon growing on vines\b",
    r"\bnight growing in a garden\b",
    r"\bday harvested in baskets\b",
    r"\btime bottled and poured\b",
    r"\bspace folded into paper crane\b",
    r"\bgravity woven into a carpet\b",
    r"\bmagnetism stretched like taffy\b",
    r"\blight weighed on a scale\b",
    r"\bsound measured in colors\b",
    r"\btemperature tasted with sight\b",
    r"\bpressure heard as music\b",
    r"\bvelocity smelled as perfume\b",
    r"\bacceleration seen as flavor\b",
    r"\bmass read as text\b",
    r"\bcharge poured like water\b",
    r"\bspin painted as arrows pointing nowhere\b",
    r"\bparity written upside down left right\b",
    r"\bchirality mirrored identical\b",
    r"\bhandedness both left and right same hand\b",
    r"\bambidextrous single-handed only\b",
    r"\bbiweekly twice a week and every two weeks calendar\b",
    r"\bflammable and inflammable identical label\b",
    r"\bsanction meaning permit and punish sign\b",
    r"\boverlook and oversee both happening\b",
    r"\bcleave meaning split and cling same knife\b",
    r"\bbuckle meaning fasten and collapse belt\b",
    r"\bdust meaning remove and add dust broom\b",
    r"\bseed meaning plant and remove seeds farm\b",
    r"\bbolt meaning secure and run away door\b",
    r"\bweather meaning withstand and erode rock\b",
    r"\btrim meaning decorate and cut tree\b",
    r"\bfast meaning quick and abstain feast\b",
    r"\bleft meaning remaining and departed sign\b",
    r"\bright meaning correct and light adjective sign\b",
    r"\bclip meaning attach and cut paper\b",
    r"\brent meaning pay and tear apartment\b",
    r"\bconsultant consulting consultant loop\b",
    r"\bindustry industrial art nature hybrid\b",
    r"\bnature industrial city forest hybrid\b",
    r"\bdesert ocean forest snow volcano combo\b",
    r"\bweather all seasons at once scene\b",
    r"\bcalendar showing all months simultaneously\b",
    r"\bclock showing all hours at once readable\b",
    r"\bcompass pointing to all directions\b",
    r"\btraffic light all colors lit meaning none\b",
    r"\bkeyboard with all keys pressed and none\b",
    r"\bbook that is every book and none\b",
    r"\blibrary containing itself physically\b",
    r"\bindex referencing itself only\b",
    r"\bfootnote footnoting itself loop\b",
    r"\bglossary defining glossary wrong\b",
    r"\bappendix preceding introduction\b",
    r"\bprologue after epilogue\b",
    r"\bchapter zero between chapters\b",
    r"\btitle page after content\b",
    r"\bcover inside pages\b",
    r"\bspine detached holding book together\b",
    r"\bbinding unbound bound\b",
    r"\bpages blank printed text\b",
    r"\binkless printed ink\b",
    r"\bpaperless paper book\b",
    r"\bauthor unknown known signature\b",
    r"\bartist anonymous autograph\b",
    r"\bphotographer invisible in mirror shot\b",
    r"\bself portrait with no self\b",
    r"\bgroup photo of nobody\b",
    r"\bfamily tree with loops child parent loop\b",
    r"\bancestor descendant same person now\b",
    r"\bidentity both same and different twins one\b",
    r"\bcopy more original than original\b",
    r"\bauthentic replica certified\b",
    r"\bfake genuine certificate\b",
    r"\bcertificate certifying itself\b",
    r"\bapproval approving approval stamp\b",
    r"\bdenial denying denial letter\b",
    r"\bpermit forbidding permission\b",
    r"\blaw allowing prohibition\b",
    r"\bpolicy contradicting policy\b",
    r"\brule breaking itself\b",
    r"\bexception to all exceptions none\b",
    r"\bpattern of randomness regular\b",
    r"\bnoise structured perfectly\b",
    r"\bwhite noise with melody\b",
    r"\bstatic with clear picture\b",
    r"\bfuzzy sharp image\b",
    r"\bblurred crisp focus\b",
    r"\bdefocused sharpness\b",
    r"\bsharpened blur only\b",
    r"\bcontrast without light\b",
    r"\bsaturation without color\b",
    r"\bhue without spectrum\b",
    r"\bexposure without photons\b",
    r"\bISO negative value\b",
    r"\bshutter speed infinite zero\b",
    r"\baperture negative f-number\b",
    r"\bdepth of field infinite zero\b",
    r"\bparadox panorama narrow\b",
    r"\bmacro wide-angle hybrid\b",
    r"\bprime zoom lens\b",
    r"\bzoom prime lens\b",
    r"\btripod handheld shake-free while shaking\b",
    r"\bstabilization causing motion blur steady\b",
    r"\bHDR shadows brighter than highlights inverted\b",
    r"\bexpose to the right left centered wrong\b",
    r"\bETTR and ETTL simultaneously\b",
    r"\bETC endless etcetera\b",
    r"\bmeta caption describing itself incorrectly\b",
    r"\bprompt that asks not to be prompted\b",
    r"\bimage that cannot exist described\b",
    r"\bcaption that contradicts the image\b",
    r"\bnegative positive photo both\b",
    r"\bcolor inverted not inverted\b",
    r"\bgrayscale colorful scene monochrome\b",
    r"\bbinary color palette rainbow\b",
    r"\bCMYK in an RGB-only world label\b",
    r"\bRGB in CMYK-only print perfect\b",
    r"\bPPI infinite zero screen\b",
    r"\bDPI negative printer\b"
]
def fast_prefilter(prompt: str) -> Tuple[bool, str]:
    p = prompt.lower().strip()
    for pat in SENSITIVE_TERMS:
        if re.search(pat, p):
            return False, "SENSITIVE"
    for pat in ILLOGICAL_PATTERNS:
        if re.search(pat, p):
            return False, "ILLOGICAL"
    return True, "OK"

def normalize_prompt(p: str) -> str:
    return re.sub(r"\s+", " ", p).strip()
